name: CI
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  dotnetbuildandtest:
    runs-on: windows-2019
    
    env:
      LOGS: logs.log

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build
      
      - name: Lint
        run: |
          dotnet tool install -g JetBrains.ReSharper.GlobalTools

          declare -i SUCCESS=0
          declare -i SEVERAL_ERRORS_IN_CSHARP_CODE=1
          jb inspectcode SCAutoTracer.sln -s=warning -o="$LOGS"
          grep '<Issues />' "$LOGS" || exit "$SEVERAL_ERRORS_IN_CSHARP_CODE"
          exit "$SUCCESS"
      
      - name: Upload ReSharper Logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: resharper-logs
          path: ${{ env.LOGS }}
  
  markdowntest:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: |
          shopt -s globstar
          npm install -g markdownlint-cli2

          declare -i SUCCESS=0
          declare -i SEVERAL_ERRORS_IN_MARKDOWN_CODE=1
          markdownlint-cli2 **/*.md || exit "$SEVERAL_ERRORS_IN_MARKDOWN_CODE"
          exit "$SUCCESS"
